// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeMapper.Infrastructure.Data;

#nullable disable

namespace VibeMapper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120202627_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VibeMapper.Core.Models.Chemical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CASNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chemicals");
                });

            modelBuilder.Entity("VibeMapper.Core.Models.DNEL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChemicalId")
                        .HasColumnType("int");

                    b.Property<string>("ExposedGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExposureRoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExposureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalId");

                    b.ToTable("DNELs");
                });

            modelBuilder.Entity("VibeMapper.Core.Models.PNEC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChemicalId")
                        .HasColumnType("int");

                    b.Property<string>("Compartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalId");

                    b.ToTable("PNECs");
                });

            modelBuilder.Entity("VibeMapper.Core.Models.DNEL", b =>
                {
                    b.HasOne("VibeMapper.Core.Models.Chemical", null)
                        .WithMany("DNELs")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VibeMapper.Core.Models.PNEC", b =>
                {
                    b.HasOne("VibeMapper.Core.Models.Chemical", null)
                        .WithMany("PNECs")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VibeMapper.Core.Models.Chemical", b =>
                {
                    b.Navigation("DNELs");

                    b.Navigation("PNECs");
                });
#pragma warning restore 612, 618
        }
    }
}
